### ISSUE TITLE
Improve performance by removing animation 

### ISSUE THREAD

**Issue by MarlonPassos-git** [PxlSyl/tailwind-nextjs-starter-blog-i18n#28]
What are your thoughts on removing the enter animations. Because when I ran a performance analysis, the problem of “Largest Contentful Paint element was so big. This code creates this issue. 

```tsx
 <motion.main
      variants={variants}
      initial="hidden"
      animate="enter"
      transition={{ type: 'linear' }}
    >
      {children}
    </motion.main>
  )
```
![image](https://github.com/user-attachments/assets/64856dab-6c4b-4867-af38-6147f65af9d3)

If you change the code for:

```tsx
<motion.main
      variants={variants}
      initial="visible"
      animate="enter"
      transition={{ type: 'linear' }}
    >
      {children}
    </motion.main>
```
![image](https://github.com/user-attachments/assets/fb1eece5-242a-4f78-ad83-9c53a98a3913)
I fixed the performance issue, but I removed an animation. Do you think that is good coice ?

**Comment by PxlSyl** [comment]
Yes I think it could be a good choice. I like the animation, but the issue is too big so we can improve on that!

**Comment by PxlSyl** [comment]
Removed
