### ISSUE TITLE
Site error for EN/root homepage on netlify deployment - Too many redirects

### ISSUE THREAD

**Issue by ranjith-b** [PxlSyl/tailwind-nextjs-starter-blog-i18n#5]
**Describe the bug**
Could not open the homepage (for language EN) due to too many redirects error. But, one can open the page `https://myurl/fr`

**To Reproduce**

1. Log on to netlify and click add new site
2. add the site from Github 
3.  build the repository for deployment
4. Click on the URL to see the deployed website
<img width="1728" alt="Screenshot 2023-12-31 at 13 08 33" src="https://github.com/PxlSyl/tailwind-nextjs-starter-blog-i18n/assets/5801052/ff4b5d10-3062-49c8-933d-59c7d2885996">
<img width="1426" alt="Screenshot 2023-12-31 at 13 08 45" src="https://github.com/PxlSyl/tailwind-nextjs-starter-blog-i18n/assets/5801052/e79e35f9-e537-4185-93c2-6a9bf75d5d6f">

**Comment by PxlSyl** [comment]
Hi! 

Honestly, I don't use Netlify at all (I do everything with Vercel), so I have no idea how to fix this. 

This may be due to the middleware file. Otherwise, for a setup with Netlify, there are instructions on the original repository, at the end of the read.me file (if that helps)
​

**Comment by ranjith-b** [comment]
Hi, Thank you very much for your reply. I'll have a look at the middleware file and the readme file . I tried with Vercel just now and it is working from my end as well. Thank you for the help :)
