### ISSUE TITLE
i18next::languageUtils: rejecting language code not found in supportedLngs: search.json

### ISSUE THREAD

**Issue by kakuilan** [PxlSyl/tailwind-nextjs-starter-blog-i18n#6]
**Describe the bug**
run "yarn dev", and show error:

```txt
i18next::languageUtils: rejecting language code not found in supportedLngs: search.json
i18next: languageChanged search.json
i18next: initialized {
  debug: true,
  initImmediate: true,
  ns: [ 'home' ],
  defaultNS: 'common',
  fallbackLng: [ 'en' ],
  fallbackNS: [ 'common' ],
  supportedLngs: [ 'en', 'fr', 'cimode' ],
  nonExplicitSupportedLngs: false,
  load: 'all',
  preload: false,
  simplifyPluralSuffix: true,
  keySeparator: '.',
  nsSeparator: ':',
  pluralSeparator: '_',
  contextSeparator: '_',
  partialBundledLanguages: false,
  saveMissing: false,
  updateMissing: false,
  saveMissingTo: 'fallback',
  saveMissingPlurals: true,
  missingKeyHandler: false,
  missingInterpolationHandler: false,
  postProcess: false,
  postProcessPassResolved: false,
  returnNull: false,
  returnEmptyString: true,
  returnObjects: false,
  joinArrays: false,
  returnedObjectHandler: false,
  parseMissingKeyHandler: false,
  appendNamespaceToMissingKey: false,
  appendNamespaceToCIMode: false,
  overloadTranslationOptionHandler: [Function: handle],
  interpolation: {
    escapeValue: true,
    format: [Function: bound format],
    prefix: '{{',
    suffix: '}}',
    formatSeparator: ',',
    unescapePrefix: '-',
    nestingPrefix: '$t(',
    nestingSuffix: ')',
    nestingOptionsSeparator: ',',
    maxReplaces: 1000,
    skipOnVariables: true
  },
  lng: 'search.json',
  ignoreJSONStructure: true
}
i18next::languageUtils: rejecting language code not found in supportedLngs: search.json

```

**Comment by davi-cruz** [comment]
Hi @kakuilan, this normally happens due to browser language trying to load content not available (in your case only `en` and `fr` are available).
Anything different than those (eg. en-US, fr-FR, etc), will result in an error for the library - the actual cause of the error will depend on browser configuration and OS localization. 

If you want to suppress the warning, I recommend you include the clause `load: 'currentOnly'` inside the getOptions functions in `app/[locale]/i18n/settings.ts`, to suppress the warning. 

If you have any questions, I recommend you reading the [i18next Configuration Doc](https://www.i18next.com/overview/configuration-options)

HTH

**Comment by kakuilan** [comment]
> Hi @kakuilan, this normally happens due to browser language trying to load content not available (in your case only `en` and `fr` are available). Anything different than those (eg. en-US, fr-FR, etc), will result in an error for the library - the actual cause of the error will depend on browser configuration and OS localization.
> 
> If you want to suppress the warning, I recommend you include the clause `load: 'currentOnly'` inside the getOptions functions in `app/[locale]/i18n/settings.ts`, to suppress the warning.
> 
> If you have any questions, I recommend you reading the [i18next Configuration Doc](https://www.i18next.com/overview/configuration-options)
> 
> HTH

Ok, thank you, and http://localhost:3000/search.json is not a json format, where the configuration of the problem?
![图片](https://github.com/PxlSyl/tailwind-nextjs-starter-blog-i18n/assets/2321437/4a2c4446-0af1-4098-922c-1568a902493f)
